sudo: required
services:
 - docker

before_install:
 - docker build -t neosystemcouk/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true neosystemcouk/docker-react npm run test

deploy:
 provider: elastikbeanstalk
 edge: true
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY
 region: "us-east-2"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-2-521230684545"
 bucket_path: "docker"
 on:
  branch: master
